import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import ModalProvider from 'app/(main)/home/_providers/ModalProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Facebook | Home',
  description: 'Generated by create next app',
}


export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ModalProvider>
        {children}
    </ModalProvider>
  )
}
