import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import MainContentContainer from 'components/common';
import Navbar from 'components/limb/navbar';
import ModalProvider from 'providers/home/ModalProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ModalProvider>
      <div className="w-full h-full flex flex-col">
        <Navbar />
        <MainContentContainer>{children}</MainContentContainer>
      </div>
    </ModalProvider>
  )
}
